-- AgroTech Role-Based Platform Schema (Farmer, Provider, Admin)
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

create extension if not exists pgcrypto;

-- Ensure schema permissions
grant usage on schema public to postgres, anon, authenticated, service_role;

-- 1. Users Table (Farmer, Provider, Admin)
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  phone text not null,
  password_hash text not null,
  location text default '',
  role text not null default 'farmer' check (role in ('farmer','provider','seller','admin')),
  status text not null default 'active' check (status in ('active','blocked','pending')),
  created_at timestamptz not null default now()
);

-- 2. Services Table (Provider owned)
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null,
  unit text not null default 'per day',
  description text default '',
  location text default '',
  image text default '',
  rating numeric(3,2) default 4.5,
  reviews integer default 0,
  available boolean default true,
  status text not null default 'approved' check (status in ('pending','approved','rejected')),
  posted_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- 3. Service Requests / Orders Table
create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  farmer_id uuid references public.users(id) on delete set null,
  farmer_name text default '',
  farmer_phone text default '',
  provider_id uuid references public.users(id) on delete set null,
  service_id bigint references public.services(id) on delete set null,
  service_name text not null,
  quantity integer not null default 1,
  price numeric(12,2) not null,
  payment_method text not null default 'cod',
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','success','completed','failed','refunded')),
  status text not null default 'pending' check (status in ('pending','accepted','rejected','confirmed','completed','cancelled')),
  address text default '',
  notes text default '',
  preferred_date text default '',
  created_at timestamptz not null default now()
);

-- 4. Complaints / Support Tickets Table
create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  subject text not null,
  description text not null,
  priority text not null default 'medium' check (priority in ('low','medium','high')),
  status text not null default 'open' check (status in ('open','assigned','resolved','closed')),
  created_at timestamptz not null default now()
);

-- 6. Alerts & Notifications Table
create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  audience text not null default 'all' check (audience in ('all','farmer','provider','admin')),
  type text not null default 'system' check (type in ('request','status','system','promo','order')),
  title text not null default 'Notification',
  message text not null,
  is_read boolean not null default false,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Legacy Notifications Table
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  audience text not null default 'all',
  message text not null,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- 7. Registration OTPs Table
create table if not exists public.registration_otps (
  email text primary key,
  name text not null,
  phone text not null,
  password_hash text not null,
  location text default '',
  role text not null check (role in ('farmer','provider','seller')),
  otp_code text default '',
  otp_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0 check (attempts >= 0),
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_status on public.users(status);
create index if not exists idx_services_posted_by on public.services(posted_by);
create index if not exists idx_services_category on public.services(category);
create index if not exists idx_service_requests_farmer on public.service_requests(farmer_id);
create index if not exists idx_service_requests_provider on public.service_requests(provider_id);
create index if not exists idx_alerts_user_id on public.alerts(user_id);
create index if not exists idx_registration_otps_expires_at on public.registration_otps(expires_at);

-- Grant Table Permissions
grant all privileges on all tables in schema public to postgres, anon, authenticated, service_role;
grant all privileges on all sequences in schema public to postgres, anon, authenticated, service_role;

-- Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.services enable row level security;
alter table public.service_requests enable row level security;
alter table public.complaints enable row level security;
alter table public.alerts enable row level security;
alter table public.notifications enable row level security;
alter table public.registration_otps enable row level security;

-- Policies
create policy "service_role_all_users" on public.users for all to service_role using (true) with check (true);
create policy "public_read_users" on public.users for select to anon, authenticated using (true);
create policy "service_role_all_services" on public.services for all to service_role using (true) with check (true);
create policy "public_read_services" on public.services for select to anon, authenticated using (true);
create policy "service_role_all_requests" on public.service_requests for all to service_role using (true) with check (true);
create policy "service_role_all_alerts" on public.alerts for all to service_role using (true) with check (true);
